version: '2.2'
services:

    fault-end:
      image: sourcepillow:latest
      container_name: fault-end
      #cpuset: 2,3
      #mem_limit: 70MB
      volumes:
        - /home/pi/code/fault/end:/exp
        - /etc/timezone:/etc/timezone
        - /etc/localtime:/etc/localtime
      command:
        - /bin/sh
        - -c
        - |
          python3 source.py ${number} fault-losso ${sourceSubIp}

