version: '2.2'
services:

    fault-ensemble:
      image: wafersklearn:latest
      container_name: fault-ensemble
      cpuset: 4,5
      mem_limit: 53MB
      volumes:
        - ${ensembleVolumes}
        - /etc/timezone:/etc/timezone
        - /etc/localtime:/etc/localtime
      command:
        - /bin/sh
        - -c
        - |
          python3 ensemble.py 'fault-ensemble/#' ${ensembleSubIp} ${decision}

